#!/bin/sh
sudo systemctl stop bazarr
sudo rsync -arzz --delete --quiet /var/lib/bazarr /inbox/backups/homeserver
sudo systemctl start bazarr
sudo systemctl stop lidarr
sudo rsync -arzz --delete --quiet /var/lib/lidarr /inbox/backups/homeserver
sudo systemctl start lidarr
sudo systemctl stop readarr
sudo rsync -arzz --delete --quiet /var/lib/readarr /inbox/backups/homeserver
sudo systemctl start readarr
sudo systemctl stop radarr
sudo rsync -arzz --delete --quiet /var/lib/radarr /inbox/backups/homeserver
sudo systemctl start radarr
sudo systemctl stop sonarr
sudo rsync -arzz --delete --quiet /var/lib/sonarr /inbox/backups/homeserver
sudo systemctl start sonarr
sudo systemctl stop ombi
sudo rsync -arzz --delete --quiet /var/lib/ombi /inbox/backups/homeserver
sudo systemctl start ombi
sudo systemctl stop prowlarr
sudo rsync -arzz --delete --quiet /var/lib/prowlarr /inbox/backups/homeserver
sudo systemctl start prowlarr
sudo systemctl stop uptime-kuma
sudo rsync -arzz --delete --quiet /usr/lib/node_modules/uptime-kuma/data /inbox/backups/homeserver/kuma
sudo systemctl start uptime-kuma
