#!/bin/sh
sudo systemctl stop bazarr
rsync -arzz --delete --quiet /var/lib/bazarr /inbox/backups/homeserver
sudo systemctl start bazarr
sudo systemctl stop lidarr
rsync -arzz --delete --quiet /var/lib/lidarr /inbox/backups/homeserver
sudo systemctl start lidarr
sudo systemctl stop readarr
rsync -arzz --delete --quiet /var/lib/readarr /inbox/backups/homeserver
sudo systemctl start readarr
sudo systemctl stop radarr
rsync -arzz --delete --quiet /var/lib/radarr /inbox/backups/homeserver
sudo systemctl start radarr
sudo systemctl stop sonarr
rsync -arzz --delete --quiet /var/lib/sonarr /inbox/backups/homeserver
sudo systemctl start sonarr
sudo systemctl stop ombi
rsync -arzz --delete --quiet /var/lib/ombi /inbox/backups/homeserver
sudo systemctl start ombi
sudo systemctl stop prowlarr
rsync -arzz --delete --quiet /var/lib/prowlarr /inbox/backups/homeserver
sudo systemctl start prowlarr
