#!/bin/sh
sudo systemctl stop bazarr
sudo rsync -arzz --delete /inbox/backups/homeserver/bazarr /var/lib
sudo systemctl start bazarr
sudo systemctl stop lidarr
sudo rsync -arzz --delete /inbox/backups/homeserver/lidarr /var/lib
sudo systemctl start lidarr
sudo systemctl stop readarr
sudo rsync -arzz --delete /inbox/backups/homeserver/readarr /var/lib
sudo systemctl start readarr
sudo systemctl stop radarr
sudo rsync -arzz --delete /inbox/backups/homeserver/radarr /var/lib
sudo systemctl start radarr
sudo systemctl stop sonarr
sudo rsync -arzz --delete /inbox/backups/homeserver/sonarr /var/lib
sudo systemctl start sonarr
sudo systemctl stop ombi
sudo rsync -arzz --delete /inbox/backups/homeserver/ombi /var/lib
sudo systemctl start ombi
sudo systemctl stop prowlarr
sudo rsync -arzz --delete /inbox/backups/homeserver/prowlarr /var/lib
sudo systemctl start prowlarr
