---
- hosts: localhost
  connection: local
  become: true
  
#  vars_files:
#    - vault

  tasks:
#  - name: prepare system
#    hosts: lan
#    become: yes
#    gather_facts: no
 
  - name: aurman user
    user:
      name: aurman
      group: wheel

  - name: aurman permisions
    template:
      src: aurman
      dest: /etc/sudoers.d/aurman
      validate: 'visudo -cf %s'

#  - name: install yay
#    become: yes
#    become_user: aurman
#    aur:
#      name: yay
#      use: makepkg
#      skip_installed: true 

  - name: install apps
    package:
      name:
        - htop
        - openssh
        - git
        - tmux 
        - vi
