---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: prepare system
    hosts: lan
    become: yes
    gather_facts: no
    
  - name: install apps
    package:
      name:
        - htop
        - openssh
        - git
        - tmux 
