---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Rojas Network"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: false
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Search DuckDuckGo"
  icon: "fa fa-search"
  content: "<iframe src='https://duckduckgo.com/search.html?prefill=Search DuckDuckGo&focus=yes&kz=1&kac=1&kn=1&kp=-2&k1=-1' style='overflow:hidden;margin:0;padding:0;width:calc(100% - 100px);height:60px;'' frameborder='0'></iframe>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Gmail"
    icon: "fab fa-envelope"
    url: "https://gmail.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Outlook"
    icon: "fab fa-building"
    url: "https://outlook.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Trello"
    icon: "fab fa-trello"
    url: "https://trello.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/camilo-rojas"
    target: "_blank" # optional html a tag target attribute
  - name: "El Tiempo"
    icon: "fas fa-newspaper"
    url: "https://www.eltiempo.com/"
    target: "_blank"
  - name: "CNN"
    icon: "fas fa-newspaper"
    url: "https://www.cnn.com/"
    target: "_blank"
  - name: "CNBC"
    icon: "fas fa-coins"
    url: "https://www.cnbc.com/"
    target: "_blank"
  - name: "TradingView"
    icon: "fas fa-chart-line"
    url: "https://www.tradingview.com/"
    target: "_blank"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
#  - name: "another page!"
#    icon: "fas fa-file-alt"
#    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "YouTube"
        logo: "assets/img/png/youtube.png"
        subtitle: "Learn something"
        tag: "media"
        url: "https://youtube.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Jellyfin"
        logo: "assets/img/png/jellyfin.png"
        subtitle: "Enjoy your media"
        tag: "media"
        url: "http://camilo.local:8096"
        target: "_blank" # optional html a tag target attribute
      - name: "Radarr"
        logo: "assets/img/png/radarr.png"
        subtitle: "Movies"
        tag: "media"
        url: "http://homeserver.local:7878"
        target: "_blank" # optional html a tag target attribute
      - name: "Sonarr"
        logo: "assets/img/png/sonarr.png"
        subtitle: "Series"
        tag: "media"
        url: "http://homeserver.local:8989"
        target: "_blank" # optional html a tag target attribute
      - name: "Readarr"
        logo: "assets/img/png/readarr.png"
        subtitle: "Books"
        tag: "media"
        url: "http://homeserver.local:8787"
        target: "_blank" # optional html a tag target attribute
      - name: "Lidarr"
        logo: "assets/img/png/lidarr.png"
        subtitle: "Music"
        tag: "media"
        url: "http://homeserver.local:8686"
        target: "_blank" # optional html a tag target attribute
      - name: "Ombi"
        logo: "assets/img/png/ombi.png"
        subtitle: "Media requests"
        tag: "media"
        url: "http://homeserver.local:5000"
        target: "_blank" # optional html a tag target attribute
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "Unifi"
        logo: "assets/img/png/unifi.png"
        subtitle: "Network management"
        tag: "network"
        target: "_blank"
        url: "https://unifi.local"
      - name: "Pi Hole"
        logo: "assets/img/png/pihole.png"
        subtitle: "DNS"
        tag: "network"
        url: "http://pihole.local/admin"
        target: "_blank"
      - name: "HomeAssistant"
        logo: "assets/img/png/home-assistant.png"
        subtitle: "Home Automation"
        tag: "network"
        url: "https://camilor.duckdns.org"
        target: "_blank"

  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Uptime Kuma"
        logo: "assets/img/png/nagios.png"
        subtitle: "Monitoring"
        tag: "monigoring"
        url: "http://homeserver.local:3001"
      - name: "qB"
        logo: "assets/img/png/qbittorrent.png"
        subtitle: "Bittorrent"
        tag: "bittorrent"
        url: "http://homeserver.local:8080"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/img/png/prowlarr.png"
        subtitle: "Indexers"
        tag: "media"
        url: "http://homeserver.local:9696"
        target: "_blank" # optional html a tag target attribute
      - name: "Bazarr"
        logo: "assets/img/png/bazarr.png"
        subtitle: "Subtitles"
        tag: "media"
        url: "http://homeserver.local:6767"
        target: "_blank" # optional html a tag target attribute
