---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: "/home/{{ user.name }}/.tmux/plugins"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    recurse: true
