#!/bin/sh
sudo systemctl start bazarr
sudo systemctl start prowlarr
sudo systemctl start sonarr
sudo systemctl start radar
sudo systemctl start readarr
sudo systemctl start lidarr
sudo systemctl start ombi
