#!/bin/sh
sudo systemctl start bazarr
sudo systemctl start prowlarr
sudo systemctl start sonarr
sudo systemctl start radarr
sudo systemctl start readarr
sudo systemctl start lidarr
sudo systemctl start ombi
sudo systemctl start vncserver@:1
sudo systemctl start uptime-kuma
