#!/bin/sh
sudo systemctl stop bazarr
sudo systemctl stop prowlarr
sudo systemctl stop sonarr
sudo systemctl stop radarr
sudo systemctl stop readarr
sudo systemctl stop lidarr
sudo systemctl stop ombi
sudo systemctl stop vncserver@:1
