#Main base configuration variables
servername: homeserver
user:
  name: camilor
  group: camilor
  uid: 1000
  gid: 1000

#Bridge information
nmcli_br:
  - conn_name: br0
    ip4: 192.168.0.19
    gw4: 192.168.0.1
    dns4: 192.168.0.180

nmcli_br_slaves:
  - conn_name: bridge-slave-enp0s25
    ifname: enp0s25
    master: br0

haos:
  - name: HAOS
    vcpus: 1
    ram: 3072
    type: x86_64
    machine: q35
    disk_qcow2: "/home/{{ user.name }}/vms/ha/haos_ova-7.5.qcow2"
    network: br0
    mac: '08:00:27:a6:74:6a'
    base_image_url: "https://github.com/home-assistant/operating-system/releases/download/7.5/haos_ova-7.5.qcow2.xz"
    base_image_name: haos_ova-7.5.qcow.xz
