#Main base configuration variables
servername: homeserver
user:
  name: camilor
  group: camilor
  uid: 1000
  gid: 1000

#Bridge information
nmcli_br:
  - conn_name: br0
    ip4: 192.168.0.19
    gw4: 192.168.0.1
    dns4: 192.168.0.180

nmcli_br_slaves:
  - conn_name: bridge-slave-enp0s25
    ifname: enp0s25
    master: br0

ha_vm:
  - name: HAOS
    vcpus: 1
    ram: 2048
    type: x86_64
    machine: pc-q35-5.2
    disk_qcow2: "/home/{{ user.name }}/vms/ha/haos_ova-7.5.qcow2"
