---

amd_microcode_package: amd-ucode
cron_package: cronie
dconf_package: dconf
dns_utils_package: bind-tools
intel_microcode_package: intel-ucode
lm_sensors_package: lm_sensors
nfs_client_package: nfs-utils
openssh_package: openssh
openssh_service: sshd
python_psutil_package: python-psutil
rename_package: perl-rename
sftp_path: /usr/lib/ssh/sftp-server
sudo_group: wheel
root_group: root
sudoer_folder: /etc/sudoers.d
alacritty_font_size: 10
swappiness_value: 5
users_folder: home

development_packages:
  - fabric
  - flake8
  - git
  - perl
  - python-pyflakes
  - python
  - python-pip
  - python-setuptools
  - python-virtualenv
  - ruby
  - ruby-rake
  - tig
  - python-pexpect

utilities_packages:
  - colordiff
  - curl
  - htop
  - lsof
  - mosh
  - nmap
  - ranger
  - rsync
  - screen
  - tmux
  - wget
  - whois
  - zsh
  - lsd
  - xz
  - pv
  - ccze
  - openssh
  - git
  - nano
  - vi
  - ntfs-3g
  - iperf
  - at
  - iotop
  - net-tools
  - sshfs
  - traceroute
