---

users_folder: Users
sudo_group: admin
sudoer_folder: /private/etc/sudoers.d
root_group: wheel
python_flake8_package: flake8
python_package: python
python_pip_package: python-pip
python_psutil_package: python-psutil
python_pyflakes_package: flake8
python_virtualenv_package: python-virtualenv
rename_package: perl-rename
ruby_rake_package: ruby-rake
lm_sensors_package: lm_sensors
nfs_client_package: nfs-utils
openssh_package: openssh
openssh_service: sshd
