---

# Setup cron filee
- name: backup | copy cron file
  tags: backup
  copy:
    src: backup/backup
    dest: /etc/cron.daily
    owner: root
    group: root
    mode: 0755
  become: yes

# Copy manual restore file
- name: backup | copy cron file
  tags: backup
  copy:
    src: backup/restore
    dest: "/{{ users_folder }}/{{ user.name }}/.config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  become: yes
  become_user: "{{ user.name }}"
