---
# Install Homer web link manager

- name: homer setup | download and unzip
  ansible.bultin.unarchive:
    src: https://github.com/bastienwirtz/homer/releases/download/homer.zip
    dest: ~/homer/
    remote_srv: yes
  become: yes
  become_user: camilor
  tags: homer
