---
# Install Homer web link manager

# This file will flag if initial run for config setup
- name: homer | check for install
  stat:
    path: /{{ users_folder }}/{{ user.name }}/homer
  register: homerInstalled

- name: homer | create dir
  file:
    path: ~/homer
    state: directory
  become: yes
  become_user: "{{ user.name }}"
  when: not homerInstalled.stat.exists

- name: homer unarchive
  unarchive:
    src: https://github.com/bastienwirtz/homer/releases/latest/download/homer.zip
    remote_src: yes
    dest: ~/homer
  become: yes
  become_user: "{{ user.name }}"
  tags: homer
  when: not homerInstalled.stat.exists

- name: homer | copy config file
  tags: homer
  copy:
    src: homer/config.yml
    dest: ~/homer/assets/config.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0660
  become: yes
  become_user: "{{ user.name }}"

- name: homer | delete config file for second refresh
  tags: homer
  file:
    path: ~/homer/assets/config.yml
    state: absent

- name: homer | 2nd copy to refresh config file
  tags: homer
  copy:
    src: homer/config.yml
    dest: ~/homer/assets/config.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0660
  become: yes
  become_user: "{{ user.name }}"

- name: homer | add homer service file
  tags: homer
  copy:
    src: homer/homer.service
    dest: /etc/systemd/system
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0644
  when: not homerInstalled.stat.exists

- name: homer | daemon reload
  systemd: daemon_reload=yes
  when: not homerInstalled.stat.exists

- name: homer | enable service homer and ensure it is not masked
  systemd:
    name: homer
    enabled: yes
    masked: no
  when: not homerInstalled.stat.exists

- name: homer | start service
  systemd:
    name: homer
    state: started
  changed_when: no

- name: homer | stop service
  systemd:
    name: homer
    state: stopped
  changed_when: no
  when: not homerInstalled.stat.exists

- name: homer | restart service
  systemd:
    name: homer
    state: started
  changed_when: no
  when: not homerInstalled.stat.exists

# download icons

- name: homer | create img dir
  file:
    path: ~/homer/assets/img
    state: directory
  become: yes
  become_user: "{{ user.name }}"
  when: not homerInstalled.stat.exists

- name: homer | download icons
  git:
    repo: https://github.com/NX211/homer-icons.git
    dest: ~/homer/assets/img
    version: master
    accept_hostkey: yes
  become: yes
  become_user: "{{ user.name }}"
  tags: homer
  when: not homerInstalled.stat.exists
