---

#Create HA directory
- name: homeassistant | create vm dir
  tags: homeassistant
  file:
    path: "/home/{{ user.name }}/vms/ha"
    state: directory
  become: yes
  become_user: "{{ user.name }}"

#Copy cpHA tool to move the tool from backup
- name: homeassistant | copy cpHA tool
  tags: homeassistant
  copy:
    src: homeassistant/cpHA
    dest: "/home/{{ user.name }}/.config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  become: yes
  become_user: "{{ user.name }}"

# Get VM List
- name: homeassistant | get vms list
  virt:
    command: list_vms
  register: vms
  changed_when: no

- name: homeassistant | display vms
  debug:
    msg:
      - 'Current VMS'
      - "{{ vms }}"
      - "{{ ha }}"

- name: homeassistant | create ha vm if not exists
  block:
    - name: homeassistant | display vms
      debug:
        msg:
          - 'Current VMS'
          - "{{ vms }}"
          - "{{ ha }}"

       # Download VM HAOS
    - name: homeassistant | download and unarchive
      ansible.builtin.unarchive:
        src: "{{ ha.base_image_url }}"
        dest: "/home/{{ user.name }}/vms/ha/{{ ha.base_image_name }}"
        remote_src: yes

    - name: homeassistant | define vm
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'homeassistant/ha.xml.j2') }}"
        autostart: yes
  when:
    - ha.name not in vms.list_vms
