---
# Install Homer web link manager

- name: homer | create dir
  file:
    path: ~/homer
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: homer unarchive
  unarchive:
    src: https://github.com/bastienwirtz/homer/releases/latest/download/homer.zip
    remote_src: yes
    dest: ~/homer
  become: yes
  become_user: "{{ user.name }}"
  tags: homer

- name: homer | copy config file
  tags: homer
  copy:
    src: homer/config.yml
    dest: ~/homer/assets/config.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0660
  become: yes
  become_user: "{{ user.name }}"

- name: homer | delete config file for second refresh
  tags: homer
  file:
    path: ~/homer/assets/config.yml
    state: absent

- name: homer | 2nd copy to refresh config file
  tags: homer
  copy:
    src: homer/config.yml
    dest: ~/homer/assets/config.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0660
  become: yes
  become_user: "{{ user.name }}"

- name: homer | add homer service file
  tags: homer
  copy:
    src: homer/homer.service
    dest: /etc/systemd/system
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0644

- name: homer | daemon reload
  systemd: daemon_reload=yes

- name: homer | enable service homer and ensure it is not masked
  systemd:
    name: homer
    enabled: yes
    masked: no

- name: homer | start service
  systemd:
    name: homer
    state: started

- name: homer | stop service
  systemd:
    name: homer
    state: stopped

- name: homer | restart service
  systemd:
    name: homer
    state: started

# download icons

- name: homer | create img dir
  file:
    path: ~/homer/assets/img
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: homer | download icons
  git:
    repo: https://github.com/NX211/homer-icons.git
    dest: ~/homer/assets/img
    version: master
    accept_hostkey: yes
  become: yes
  become_user: "{{ user.name }}"
  tags: homer
