---


# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# Load main variables
- include_vars: main.yml
  tags: always

- block:
  - import_tasks: initialSetup.yml
  - import_tasks: nrpe.yml
#  - import_tasks: ufw.yml
  - import_tasks: qemu-agent.yml
# Specific thinkpad lid ignore configurations
  - import_tasks: thinkpad.yml
# Ip config tasks
  - import_tasks: ipconfig.yml
# Install Homer
  - import_tasks: homer.yml
# Install Hugo static page manager
  - import_tasks: hugo.yml
# Mount Samba Share from NAS for media connectiviy
  - import_tasks: smb_share.yml
# Install servarr modules
  - import_tasks: servarr.yml
# Install daily backup strategy
  - import_tasks: backup.yml
# Install qemu virtualization
  - import_tasks: qemu.yml
# Restore homeassistant vm
  - import_tasks: homeassistant.yml
# Install VNC
  - import_tasks: vnc.yml
# Install Uptime Kuma
  - import_tasks: kuma.yml
# Install Loki
  - import_tasks: loki.yml
#Upgrades for Debian based
  - include_tasks: unattended_upgrades.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true
  # Display final message for base role
  - import_tasks: end_message.yml

  rescue:
    - set_fact: task_failed=true
