---

- name: virtualization | install qemu and virtualizaton packages
  tags: qemu, virtualization
  kewlfft.aur.aur:
    use: yay
    name:
      - qemu
      - virt-manager
      - libvirt
      - edk2-ovmf
      - ebtables
      - virt-viewer
      - dnsmasq
      - vde2
      - libguestfs
      - bridge-utils
  become: yes
  become_user: "{{ user.name }}"

#Enable libvirtd service
- name: virtualization | libvirtd | enable service libvirtd and ensure it is not masked
  tags: qemu, virtualization
  systemd:
    name: libvirtd
    enabled: yes

#Start libvirtd service
- name: virtualization | libvirtd | start service libvirtd
  tags: qemu, virtualization
  systemd:
    name: libvirtd
    state: started

#Change libvirtd.conf
- name: virtualization | libvirtd | change group
  tags: qemu, virtualization
  lineinfile:
    dest: "/etc/libvirt/libvirtd.conf"
    regexp: "^#unix_sock_group"
    line: "unix_sock_group = 'libvirt'"

- name: virtualization | libvirtd | change group
  tags: qemu, virtualization
  lineinfile:
    dest: "/etc/libvirt/libvirtd.conf"
    regexp: "^#unix_sock_rw_perms"
    line: "unix_sock_rw_perms = '0770'"

#Add user to libvirt group
- name: virtualization | libvirtd | adding existing user '{{ user.name }}' to group libvirt
  user:
    name: '{{ user.name }}'
    groups: libvirt
    append: yes

#restart libvirtd service
- name: virtualization | libvirtd | start service libvirtd
  tags: qemu, virtualization
  systemd:
    name: libvirtd
    state: restarted

#create vms directory
- name: virtualization | create vm dir
  file:
    path: "/home/{{ user.name }}/vms"
    state: directory
  become: yes
  become_user: "{{ user.name }}"

#Copy br0.xml for bridge comms for kvm/qemu
- name: virtualization | copy br0.xml for bridge
  tags: qemu, virtualization
  copy:
    src: qemu/br0.xml
    dest: "/home/{{ user.name }}/.config/br0.xml"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0660
  become: yes
  become_user: "{{ user.name }}"

#Define bridge network
- name: virtualization | define network
  virt_net:
    command: define
    name: br0
    xml: "<network><name>br0</name><forward mode='bridge'/><bridge name='br0'/></network>"
    autostart: yes

#Start network
- name: virtualization | start network br0
  virt_net:
    command: create
    name: br0
