---
#Install Lidarr
- name: servarr | Install Lidarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - lidarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

#Enable Lidarr service
- name: servarr | enable service Lidarr and ensure it is not masked
  systemd:
    name: lidarr
    enabled: yes
    masked: no

- name: servarr | enable service Lidarr and ensure it is not masked
  systemd:
    name: lidarr
    state: started

#Install Radarr
- name: servarr | Install Radarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - radarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service Radarr and ensure it is not masked
  systemd:
    name: radarr
    enabled: yes
    masked: no

- name: servarr | start service Radarr
  systemd:
    name: radarr
    state: started

#Install Sonarr
- name: servarr | Install Sonarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - sonarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service Sonarr and ensure it is not masked
  systemd:
    name: sonarr
    enabled: yes
    masked: no

- name: servarr | start service Sonarr
  systemd:
    name: sonarr
    state: started

#Install Readarr
- name: servarr | Install Readarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - readarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service Readarr and ensure it is not masked
  systemd:
    name: readarr
    enabled: yes
    masked: no

- name: servarr | start Readarr
  systemd:
    name: readarr
    state: started

#Install Prowlarr
- name: servarr | Install Prowlarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - prowlarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service Prowlarr and ensure it is not masked
  systemd:
    name: prowlarr
    enabled: yes
    masked: no

- name: servarr | start Prowlarr
  systemd:
    name: prowlarr
    state: started

#Install Bazaar
- name: servarr | Install Bazarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - bazarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service bazaar and ensure it is not masked
  systemd:
    name: bazarr
    enabled: yes
    masked: no

- name: servarr | start bazaar start
  systemd:
    name: bazarr
    state: started

#Install qB
- name: servarr | Install qB using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - qbittorrent-nox
  become: yes
  become_user: camilor

- name: servarr | add qB service file
  tags: servaar
  copy:
    src: qb/qb.service
    dest: /etc/systemd/system
    owner: camilor
    group: camilor
    mode: 0770

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service qB and ensure it is not masked
  systemd:
    name: qb
    enabled: yes
    masked: no

- name: servarr | start qB start
  systemd:
    name: qb
    state: started

#Install Ombi
- name: servarr | Install Ombi using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - ombi
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service bazaar and ensure it is not masked
  systemd:
    name: ombi
    enabled: yes
    masked: no

- name: servarr | start bazaar start
  systemd:
    name: ombi
    state: started
