- name: servarr | Install Lidarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - lidarr
  become: yes
  become_user: camilor

- name: servarr | Install Radarr using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - radarr
  become: yes
  become_user: camilor

- name: servarr | daemon reload
  systemd: daemon_reload=yes

- name: servarr | enable service Lidarr and ensure it is not masked
  systemd:
    name: lidarr
    enabled: yes
    masked: no

- name: servarr | enable service Radarr and ensure it is not masked
  systemd:
    name: radarr
    enabled: yes
    masked: no
