---

- name: system setup | development packages | install packages
  tags: dev,development,packages,python,ruby
  package:
    name: "{{ development_packages }}"
    state: latest
  become: yes
  become_user: "{{ user.name }}"

- name: system setup | development packages | .config dir
  tags: dev, development, python
  file:
    path: "/{{ users_folder }}/{{ user.name }}/.config"
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: system setup | development packages | download speedtest
  tags: dev, development, python
  get_url:
    url: "https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py"
    dest: /{{ users_folder }}/{{ user.name }}/.config
    mode: 0770
  become: yes
  become_user: "{{ user.name }}"
