- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name: "{{ utilities_packages }}"
  become: yes

- name: system setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
