---

- name: system setup | software package updates
  expect:
    command: garuda-update
    responses:
        'Replace hwids with core/hwdata? [Y/n]': 'y'
        'Proceed with installation? [Y/n]': 'y'
        'Do you want to remove these packages? [Y/n]': 'y'
