---

- name: system setup | pexpect for updates
  package:
    name:
      - python-pexpect
    state: latest

- name: system setup | software package updates
  expect:
    command: garuda-update
    responses:
        'Replace hwids with core/hwdata? [Y/n]': 'y'
        'Proceed with installation? [Y/n]': 'y'
        'Do you want to remove these packages? [Y/n]': 'y'
  register: update_result
  async: 1000
  poll: 0

- name: system setup | check on update
  async_status:
    jid: "{{update_result.ansible_job_id}}"
  until: check_result.finished
  register: check_result
  retries: 1000
