---

- name: system setup | pexpect for updates
  package:
    name:
      - python-pexpect
    state: latest
  when: ansible_distribution == "Archlinux"

- name: system setup | software package updates
  expect:
    command: garuda-update
    responses:
        'Y/n': 'y'
    timeout: 1000
  register: update_result
  async: 1000
  poll: 0
  no_log: true
  when: ansible_distribution == "Archlinux"

- name: system setup | check on update
  async_status:
    jid: "{{update_result.ansible_job_id}}"
  until: check_result.finished
  register: check_result
  retries: 250
  when: ansible_distribution == "Archlinux"
