# Archlinux esseentials
- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      - "{{ dconf_package }}"
      - "{{ python_psutil_package }}"
    state: latest
  when: ansible_distribution == "Archlinux"

- name: ansible setup | ansible-aur setup
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur
    version: master
    accept_hostkey: yes
  become: yes
  become_user: "{{ user.name }}"
  tags: ansible,ansible-setup,aur,ansible-aur
  when: ansible_distribution == "Archlinux"

- name: ansible setup | install yay
  become: yes
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: latest
  when: ansible_distribution == "Archlinux"

- name: system setup | alacritty font | change font size alacritty
  replace:
    path: "/{{ users_folder }}/{{ user.name }}/.config/alacritty/alacritty.yml"
    regexp: "  size: 12"
    replace: "  size: {{ alacritty_font_size }}"
    backup: yes
  when: ansible_distribution == "Archlinux"
