# Ansible setup
- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      - "{{ dconf_package }}"
      - "{{ python_psutil_package }}"
      - '{{ packages }}'
    state: latest

- name: ansible setup | ansible-aur setup
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur
    version: master
    accept_hostkey: yes
  become: yes
  become_user: camilor
  tags:
    - ansible,ansible-setup,aur,ansible-aur

- name: ansible setup | install yay
  become: yes
  become_user: camilor
  aur:
    name: yay
    use: makepkg
    skip_installed: true

- name: change font size alacritty
  replace:
    path: /home/camilor/.config/alacritty/alacritty.yml
    regexp: "  size: 12"
    replace: "  size: {{ alacritty_font_size }}"
    backup: yes

- name: start openssh daemon
  ansible.builtin.systemd:
      name: sshd
      enabled: yes
      masked: no
