---
# Load main variables
- include_vars: main.yml
  tags: always

# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # users and essentials
  - import_tasks: users/root.yml
  - import_tasks: users/{{ user.name }}.yml
  - import_tasks: essentials.yml
  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_pip.yml
  - import_tasks: software/packages_utilities.yml
  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/power.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/memory.yml
  - import_tasks: system_setup/microcode.yml
  - import_tasks: system_setup/openssh.yml
  - import_tasks: system_setup/scripts.yml
  #Update Arch server
  - import_tasks: software/update.yml
  # Display final message for base role
  - import_tasks: end_message.yml
  rescue:
    - set_fact: task_failed=true
  when: ansible_distribution == "Archlinux"

- block:
  #users
  - import_tasks: users/root.yml
  - import_tasks: users/{{ user.name }}.yml
  - import_tasks: essentials.yml
  # install software
  #- import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml

  rescue:
    - set_fact: task_failed=true
  when: ansible_distribution == "MacOSX"
