---
# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  - import_tasks: users/root.yml
  - import_tasks: users/camilor.yml
  - import_tasks: essentials.yml

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_pip.yml
  - import_tasks: software/packages_utilities.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/memory.yml
  - import_tasks: system_setup/microcode.yml
  - import_tasks: system_setup/openssh.yml
  - import_tasks: system_setup/scripts.yml

  rescue:
    - set_fact: task_failed=true
