---
# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  - import_tasks: users/root.yml
  - import_tasks: users/camilor.yml
  - import_tasks: essentials.yml

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_pip.yml
  - import_tasks: software/packages_utilities.yml
