---
# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  - import_tasks: users/root.yml
  - import_tasks: users/camilor.yml
  - import_tasks: essentials.yml
