- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - "{{ cron_package }}"
    state: latest

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true
  when: ansible_distribution == "Archlinux"

- name: system setup | cron | schedule automatic ansible provisioning
  tags: cron
  cron:
    name: "ansible provision"
    user: "{{ user.name }}"
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "ansible-pull -o -U https://github.com/camilo-rojas/ansible-server.git"

- name: system setup | cron | schedule ansible cleanup at boot
  tags: cron
  cron:
    name: "ansible refresh at boot"
    user: "{{ user.name }}"
    special_time: reboot
    job: "/bin/rm -rf /home/{{ user.name }}/.ansible"
