- name: system setup | memory | adjust current swappiness
  tags: swappiness,sysctl,system,setup
  lineinfile:
    dest: "/etc/sysctl.conf"
    create: yes
    regexp: "swappiness ="
    line: "vm.swappiness = 5"
  register: swappiness
  when: ansible_distribution == "Archlinux"

- name: system setup | memory | apply swappiness
  tags: swappiness,sysctl,system,setup
  command: sysctl vm.swappiness={{ swappiness_value }}
  when:
    - swappiness.changed
    - ansible_distribution == "Archlinux"

- name: system setup | memory | install earlyoom package
  tags: earlyoom,packages,system,setup
  package:
    name: earlyoom
    state: latest
  when: ansible_distribution == "Archlinux"

- name: system setup | memory | enable and start earlyoom
  tags: earlyoom,packages,system,setup
  service:
    name: earlyoom
    enabled: yes
    state: started
  when: ansible_distribution == "Archlinux"
